ame: MyPluginA
description: My plugin A
types:
  - app
inputs:
  - label: Meta Description
    type: text
    name: meta_description
    default: "Description of my app"
  - label: Version
    type: int
    name: version
    default: "1"
  - label: Meta Keywords
    type: multiselect
    name: keywords
    items:
      - HTML
      - JS
      - CSS
